name: Docker Image

on:
    push:
        branches: ["main"]
    schedule:
        - cron: '0 0 15 * *'
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup qemu for multi-arch build
              uses: docker/setup-qemu-action@v3

            - name: Setup buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GHCR_TOKEN }}

            - name: Login to Docker Container Registry
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_HUB_USER }}
                  password: ${{ secrets.DOCKER_HUB_TOKEN }}

            - name: Build and push multi-arch container
              uses: docker/build-push-action@v5
              with:
                  context: .
                  platforms: linux/amd64,linux/arm64
                  push: true
                  tags: |
                      davescodemusings/monit-collector:latest
                      ghcr.io/davescodemusings/monit-collector:latest
                      davescodemusings/monit-collector:x86
                      ghcr.io/davescodemusings/monit-collector:x86
                      davescodemusings/monit-collector:arm64
                      ghcr.io/davescodemusings/monit-collector:arm64
